assistive-pricing: true
comment-incentives: true
command-settings:
  - name: "start"
    enabled: true
  - name: "wallet"
    enabled: true
promotion-comment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
