commandSettings:
  - name: "start"
    enabled: true
  - name: "wallet"
    enabled: true
  - name: "approve"
    enabled: true
commentIncentives: true
incentives:
  comment:
    elements:
      code: 30
      img: 105
      h1: 3
      li: 1
      blockquote: 0
    totals:
      word: 0.1
