time-labels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <3 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <5 Hours"
  - name: "Time: <6 Hours"
  - name: "Time: <7 Hours"
  - name: "Time: <8 Hours"
  - name: "Time: <9 Hours"
  - name: "Time: <10 Hours"
  - name: "Time: <11 Hours"
  - name: "Time: <12 Hours"
  - name: "Time: <13 Hours"
  - name: "Time: <14 Hours"
  - name: "Time: <15 Hours"
  - name: "Time: <16 Hours"
  - name: "Time: <17 Hours"
  - name: "Time: <18 Hours"
  - name: "Time: <19 Hours"
  - name: "Time: <20 Hours"
  - name: "Time: <21 Hours"
  - name: "Time: <22 Hours"
  - name: "Time: <23 Hours"
  - name: "Time: <24 Hours"
  - name: "Time: <25 Hours"
  - name: "Time: <26 Hours"
  - name: "Time: <27 Hours"
  - name: "Time: <28 Hours"
  - name: "Time: <29 Hours"
  - name: "Time: <30 Hours"
  - name: "Time: <31 Hours"
  - name: "Time: <32 Hours"
  - name: "Time: <33 Hours"
  - name: "Time: <34 Hours"
  - name: "Time: <35 Hours"
  - name: "Time: <36 Hours"
  - name: "Time: <37 Hours"
  - name: "Time: <38 Hours"
  - name: "Time: <39 Hours"
  - name: "Time: <40 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <2 Days"
  - name: "Time: <3 Days"
  - name: "Time: <4 Days"
  - name: "Time: <5 Days"
  - name: "Time: <6 Days"
  - name: "Time: <7 Days"
  - name: "Time: <1 Week"
  - name: "Time: <2 Weeks"
  - name: "Time: <1 Month"
priority-labels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
default-labels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
assistive-pricing: true
comment-incentives: true
command-settings:
  - name: "start"
    enabled: true
  - name: "wallet"
    enabled: true
promotion-comment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
